### ISSUE TITLE
doesnt render the beard/facialHairType 

### ISSUE THREAD

**Issue by rbrtbrnschn** [gkoberger/avataaars#18]
url
https://getavataaars.com/?accessoriesType=Prescription01&avatarStyle=Circle&clotheColor=PastelOrange&clotheType=ShirtScoopNeck&eyeType=Close&eyebrowType=SadConcernedNatural&facialHairType=BeardMagestic&hairColor=Black&hatColor=Gray02&mouthType=Grimace&skinColor=Light&topType=ShortHairShortWaved

result of embed image tag button
<img src='https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShortWaved&accessoriesType=Prescription01&hairColor=Black&facialHairType=BeardMagestic&facialHairColor=BrownDark&clotheType=ShirtScoopNeck&clotheColor=PastelOrange&eyeType=Close&eyebrowType=SadConcernedNatural&mouthType=Grimace&skinColor=Light'
/>

same as above, just rendered so you can get an idea.
img: 

# Problem
on the webiste I got this guy on random.
I clicked the embed image tag button and got this. in the search query you can clearly see it specifies the a failedHairType but it doesnt show that when rendering via image tag.

I suppose theres a casesensitivity issue or a spelling mistake somewhere in either the api or the getImageTag() function that returns the embeddle image tag.

**Comment by gkoberger** [comment]
That's intentional! This repo is sponsored by Gillette, and they paid us to remove the bears.

![image](https://user-images.githubusercontent.com/381393/109375313-a54eb080-7870-11eb-80fe-27f5cc8df0bd.png)

(Really, seems like there's a typo on the generator site, "magestic" should be "majestic". I added a check for it, so it works now! Fixed in 868c4cc)
